Initial test setup and new enum
juanidambrosio/smileshelper pull request #20
Opened 2023-01-27 18:19 UTC by francobasilico

-Added const for tripTypes ONE WAY: 2,RETURN: 2
-Added jest and basic configuration
-Added tests for parser

2023-01-31 23:31 UTC, juanidambrosio requested changes
- Please rollback the single quotes to double quotes in constants.js
- Nice to have -> add husky basic configuration to prevent commits introducing test failures

2023-02-01 08:42 UTC, francobasilico commented
> 

Must have been my autoformatter.
Do you have any preference for code styleguides? maybe a linter can be configured and also added to husky

2023-02-01 08:43 UTC, francobasilico commented
> * Please rollback the single quotes to double quotes in constants.js
> * Nice to have -> add husky basic configuration to prevent commits introducing test failures
@juanidambrosio 
Must have been my autoformatter.
Do you have any preference for code styleguides? maybe a linter can be configured and also added to husky

2023-02-02 13:53 UTC, juanidambrosio approved these changes

2023-02-02 13:54 UTC, merged